2024-07-04 11:52:57,311 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-07-04 11:52:57,311 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instabot/bot/bot.py
2024-07-04 11:52:57,311 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-07-04 11:54:29,153 - instabot version: 0.117.0 (api) - WARNING - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-07-04 11:55:44,441 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/sync/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1067ae2d0>: Failed to establish a new connection: [Errno 65] No route to host'))
